# This is a basic workflow to help you get started with Actions
name: run-preprocessing

# Run the workflow if new data is pushed to our /raw folder
on:
  push:
    paths:
      - data/raw # Trigger on new data in /raw only

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  preprocess:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: preprocess-step
        run: |
          cat "Running preprocessing pipeline'
          python preprocessing.py

  
