# This is a basic workflow to help you get started with Actions
name: run-preprocessing

# Run the workflow if new data is pushed to our /raw folder
on:
  push:
    branches:    
    - 'workflow-preprocess'
    paths:
      - 'data/raw/**.csv'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  preprocess:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Run python preprecoessing script
      - name: preprocess-step
        run: |
          echo "Running preprocessing pipeline"
          pip install pandas
          pip install numpy
          python preprocessing.py

  
